### ISSUE TITLE
type attribute of record is not parsed

### ISSUE THREAD

**Issue by wgresshoff** [ksclarke/freelib-marc4j#13]
The type attribute of the record tag is not parsed. It is used by the "Deutsche Bibliothek".

**Comment by ksclarke** [comment]
Hi @wgresshoff 

I assume you mean when parsing MARCXML? Do you have a sample record that uses the type attribute that you could share? Thanks!

**Comment by wgresshoff** [comment]
Am 22.02.2016 um 19:55 schrieb Kevin S. Clarke:
>
> Hi @wgresshoff <https://github.com/wgresshoff>
>
> I assume you mean when parsing MARCXML? Do you have a sample record 
> that uses the type attribute that you could share? Thanks!
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/ksclarke/freelib-marc4j/issues/13#issuecomment-187318491>.
>
Hi Kevin,

you're right, I mean MARCXML. I've attached a patched version of 
MarcXmlHandler and provide an example from the DNB 
(ZDB/Zeitschriftendatenbank):

<record type="Holdings"><leader>00337ny a22001573n 
4500</leader><controlfield 
tag="001">331801426</controlfield><controlfield 
tag="003">DE-101</controlfield><controlfield 
tag="005">20150805121724.0</controlfield><controlfield 
tag="008">150804||||||||||||||||ger|||||||</controlfield><datafield 
ind1="" ind2="" tag="092"><subfield 
code="a">501001-9</subfield><subfield code="d">38 M</subfield><subfield 
code="k">NRW</subfield><subfield code="l">a</subfield><subfield 
code="o">b</subfield></datafield><datafield ind1="" ind2="" 
tag="852"><subfield code="8">1</subfield></datafield><datafield ind1="" 
ind2="1" tag="852"><subfield code="c">Einzelsignatur</subfield><subfield 
code="9">00</subfield></datafield><datafield ind1="" ind2="" 
tag="852"><subfield code="a">DE-38M</subfield></datafield><datafield 
ind1="0" ind2="1" tag="859"><subfield code="8">1.1\x</subfield><subfield 
code="a">51</subfield><subfield 
code="i">2015</subfield></datafield><datafield ind1="3" ind2="0" 
tag="866"><subfield code="a">51.2015 -</subfield></datafield><datafield 
ind1="" ind2="" tag="933"><subfield 
code="a">CC0</subfield></datafield></record>


<record type="Bibliographic"><leader>03475nas a2200625 c 
4500</leader><controlfield 
tag="001">1074156145</controlfield><controlfield 
tag="003">DE-101</controlfield><controlfield 
tag="005">20150814223156.0</controlfield><controlfield 
tag="007">tu</controlfield><controlfield tag="008">150721c20159999gw 
a||p| ||| 0||||0ger c</controlfield><datafield ind1="" ind2="" 
tag="015"><subfield code="a">15,A34</subfield><subfield 
code="2">dnb</subfield></datafield> ... </record>Kind regards Werner 
Greßhoff

**Comment by ksclarke** [comment]
Thanks @wgresshoff that's useful. You mention a patched version of MarcXmlHandler but it looks like that didn't get attached? If you've made the code change already would you like to submit a pull request with it? Or, attaching is fine too... either way.

**Comment by wgresshoff** [comment]
Am 24.02.2016 um 16:09 schrieb Kevin S. Clarke:
>
> Thanks @wgresshoff <https://github.com/wgresshoff> that's useful. You 
> mention a patched version of MarcXmlHandler but it looks like that 
> didn't get attached? If you've made the code change already would you 
> like to submit a pull request with it? Or, attaching is fine too... 
> either way.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/ksclarke/freelib-marc4j/issues/13#issuecomment-188297726>.
>
Hi Kevin,

that's odd, my mail client shows the MarcXmlHandler.java as attached 
file. Just in case, this time I'll send it embedded...
You'll see just two changes. First one is this definietion of a private 
field:

     /** The type attribute name string */
     private static final String TYPE_ATTR = "type";

The second one is in the "startElement"-method in the switch-statement:

             case RECORD_ID:
                 final String typeAttr = atts.getValue(TYPE_ATTR);

                 record = factory.newRecord();
                 record.setType(typeAttr);
                 break;

I'm using it and it works!
I've not implemented the other direction. I know the information is in 
the sixth position of the leader, but I don't know if the types
names are standardized (the Deutsche Bibliothek uses "Bibliographic" and 
"Holdings"). http://www.loc.gov/marc/ also mentions
"Authority", "Classification" and "Community" but does anybody use it?!

Best wishes
Werner Greßhoff

/**
  * Copyright (C) 2004 Bas Peters
  *
  * This file is part of MARC4J
  *
  * MARC4J is free software; you can redistribute it and/or
  * modify it under the terms of the GNU Lesser General Public
  * License as published by the Free Software Foundation; either
  * version 2.1 of the License, or (at your option) any later version.
  *
  * MARC4J is distributed in the hope that it will be useful,
  * but WITHOUT ANY WARRANTY; without even the implied warranty of
  * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
  * Lesser General Public License for more details.
  *
  * You should have received a copy of the GNU Lesser General Public
  * License along with MARC4J; if not, write to the Free Software
  * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
  *
  */

package org.marc4j;

import java.util.HashMap;

import org.marc4j.marc.ControlField;
import org.marc4j.marc.DataField;
import org.marc4j.marc.Leader;
import org.marc4j.marc.MarcFactory;
import org.marc4j.marc.Record;
import org.marc4j.marc.Subfield;
import org.xml.sax.Attributes;
import org.xml.sax.ContentHandler;
import org.xml.sax.Locator;
import org.xml.sax.SAXException;

/**
  * Creates <code>Record</code> objects from SAX events and pushes each item onto the top of the
  * <code>RecordStack</code>.
  *
  * @author Bas Peters
  */
public class MarcXmlHandler implements ContentHandler {

     private final RecordStack queue;

     private StringBuffer sb;

     private Subfield subfield;

     private ControlField controlField;

     private DataField dataField;

     private Record record;

     private String tag;

     /** Constants representing each valid tag type */
     private static final int COLLECTION_ID = 1;

     private static final int LEADER_ID = 2;

     private static final int RECORD_ID = 3;

     private static final int CONTROLFIELD_ID = 4;

     private static final int DATAFIELD_ID = 5;

     private static final int SUBFIELD_ID = 6;

     /** The tag attribute name string */
     private static final String TAG_ATTR = "tag";

     /** The code attribute name string */
     private static final String CODE_ATTR = "code";

     /** The first indicator attribute name string */
     private static final String IND_1_ATTR = "ind1";

     /** The second indicator attribute name string */
     private static final String IND_2_ATTR = "ind2";

     /** The type attribute name string */
     private static final String TYPE_ATTR = "type";

     /** Hashset for mapping of element strings to constants (Integer) */
     private static final HashMap<String, Integer> elementMap;

     private MarcFactory factory = null;

     static {
         elementMap = new HashMap<String, Integer>();
         elementMap.put("collection", new Integer(COLLECTION_ID));
         elementMap.put("leader", new Integer(LEADER_ID));
         elementMap.put("record", new Integer(RECORD_ID));
         elementMap.put("controlfield", new Integer(CONTROLFIELD_ID));
         elementMap.put("datafield", new Integer(DATAFIELD_ID));
         elementMap.put("subfield", new Integer(SUBFIELD_ID));
     }

     /**
      * Default constructor.
      *
      * @param queue
      */
     public MarcXmlHandler(final RecordStack queue) {
         this.queue = queue;
         factory = MarcFactory.newInstance();
     }

     /**
      * An event fired at the start of the document.
      */
     @Override
     public void startDocument() throws SAXException {
     }

     /**
      * An event fired at the start of an element.
      */
     @Override
     public void startElement(final String uri, final String name, final String qName, final Attributes atts)
             throws SAXException {
         final String realname = (name.length() == 0) ? qName : name;
         final Integer elementType = elementMap.get(stripNsPrefix(realname));

         if (elementType == null) {
             throw new MarcException("Unexpected XML element: " + realname);
         }

         switch (elementType.intValue()) {
             case COLLECTION_ID:
                 break;
             case RECORD_ID:
                 final String typeAttr = atts.getValue(TYPE_ATTR);

                 record = factory.newRecord();
                 record.setType(typeAttr);
                 break;
             case LEADER_ID:
                 sb = new StringBuffer();
                 break;
             case CONTROLFIELD_ID:
                 tag = atts.getValue(TAG_ATTR);

                 if (tag == null) {
                     throw new MarcException("ControlField missing tag value");
                 }

                 controlField = factory.newControlField(tag);
                 sb = new StringBuffer();
                 break;
             case DATAFIELD_ID:
                 tag = atts.getValue(TAG_ATTR);

                 if (tag == null) {
                     throw new MarcException("DataField missing tag value");
                 }

                 String ind1 = atts.getValue(IND_1_ATTR);
                 String ind2 = atts.getValue(IND_2_ATTR);

                 if (ind1 == null) {
                     throw new MarcException("DataField (" + tag + ") missing first indicator");
                 }

                 if (ind2 == null) {
                     throw new MarcException("DataField (" + tag + ") missing second indicator");
                 }

                 if (ind1.length() == 0) {
                     ind1 = " ";
                 }

                 if (ind2.length() == 0) {
                     ind2 = " ";
                 }

                 dataField = factory.newDataField(tag, ind1.charAt(0), ind2.charAt(0));
                 break;
             case SUBFIELD_ID:
                 String code = atts.getValue(CODE_ATTR);

                 if (code == null) {
                     throw new MarcException("Subfield missing code attribute");
                 }

                 if (code.length() == 0) {
                     code = " ";
                 }

                 subfield = factory.newSubfield(code.charAt(0));
                 sb = new StringBuffer();
         }
     }

     /**
      * An event fired as characters are consumed.
      *
      * @param ch
      * @param start
      * @param length
      */
     @Override
     public void characters(final char[] ch, final int start, final int length) throws SAXException {
         if (sb != null) {
             sb.append(ch, start, length);
         }
     }

     /**
      * An event fired at the end of an element.
      *
      * @param uri
      * @param name
      * @param qName
      */
     @Override
     public void endElement(final String uri, final String name, final String qName) throws SAXException {
         final String realname = (name.length() == 0) ? qName : name;
         final Integer elementType = elementMap.get(stripNsPrefix(realname));

         if (elementType == null) {
             throw new MarcException("Unexpected XML element: " + realname);
         }

         switch (elementType.intValue()) {
             case COLLECTION_ID:
                 break;
             case RECORD_ID:
                 queue.push(record);
                 break;
             case LEADER_ID:
                 final Leader leader = factory.newLeader(sb.toString());
                 record.setLeader(leader);
                 break;
             case CONTROLFIELD_ID:
                 controlField.setData(sb.toString());
                 record.addVariableField(controlField);
                 break;
             case DATAFIELD_ID:
                 record.addVariableField(dataField);
                 break;
             case SUBFIELD_ID:
                 subfield.setData(sb.toString());
                 dataField.addSubfield(subfield);
         }

     }

     /**
      * An event fired at the end of the document.
      */
     @Override
     public void endDocument() throws SAXException {
         queue.end();
     }

     /**
      * An event fired while consuming ignorable whitespace.
      *
      * @param data
      * @param offset
      * @param length
      * @throws SAXException
      */
     @Override
     public void ignorableWhitespace(final char[] data, final int offset, final int length) throws SAXException {
         // not implemented
     }

     /**
      * An event fired at the end of prefix mapping.
      *
      * @param prefix
      * @throws SAXException
      */
     @Override
     public void endPrefixMapping(final String prefix) throws SAXException {
     }

     /**
      * An event fired while consuming a skipped entity.
      *
      * @param name
      * @throws SAXException
      */
     @Override
     public void skippedEntity(final String name) throws SAXException {
         // not implemented
     }

     /**
      * An event fired while consuming a document locator.
      *
      * @param locator
      */
     @Override
     public void setDocumentLocator(final Locator locator) {
         // not implemented
     }

     /**
      * An event fired while consuming a processing instruction.
      *
      * @param target
      * @param data
      * @throws SAXException
      */
     @Override
     public void processingInstruction(final String target, final String data) throws SAXException {
         // not implemented
     }

     /**
      * An event fired at the start of prefix mapping.
      *
      * @param prefix
      * @param uri
      */
     @Override
     public void startPrefixMapping(final String prefix, final String uri) throws SAXException {
         // not implemented
     }

     /**
      * Handle namespace prefixes; also fixes issue with broken SAX emitters that spit out QName instead of local name.
      * None of our MARCXML local names should have colons.
      *
      * @param aName An element name
      * @return The element name without a namespace prefix
      */
     private String stripNsPrefix(final String aName) {
         final int index = aName.indexOf(":");

         if (index == -1 || index + 1 == aName.length()) {
             return aName;
         } else {
             return aName.substring(index + 1);
         }
     }
}

**Comment by ksclarke** [comment]
Thanks @wgresshoff for the contribution. I'll get it folded in, hopefully by the weekend at the latest.

And it does seem the values are enumerated (from the MARCXML schema):

    <xsd:simpleType name="recordTypeType" id="type.st">
      <xsd:restriction base="xsd:NMTOKEN">
        <xsd:enumeration value="Bibliographic"/>
        <xsd:enumeration value="Authority"/>
        <xsd:enumeration value="Holdings"/>
        <xsd:enumeration value="Classification"/>
        <xsd:enumeration value="Community"/>
      </xsd:restriction>
    </xsd:simpleType>

Thanks again!

**Comment by ksclarke** [comment]
This should be fixed in version 2.6.9 which is in Maven central now. Thanks!
