### ISSUE TITLE
XML Error catching code cause failures for records from Koha

### ISSUE THREAD

**Issue by haschart** [ksclarke/freelib-marc4j#28]
I cherry-picked some recent changes to MarcXmlHandler.java from this branch where illegal elements, or missing tags, missing indicators or missing subfield code cause an MarcException to be thrown.  These changes cause some records exported from Koha to fail.    The following commit to the marc4j branch shows a different way such errors could be handled:  Instead of throwing an exception, this code will create a MarcError object and add it to the Record being built, and then it will continue processing the record.   

https://github.com/marc4j/marc4j/commit/0d718cbd8a8336cb7eeaa175431e805d1192fd9b

The code currently omits the DataField of ControlField in which the error is found, it might be better to fill in a reasonable "default" value, and include the DataField or ControlField, and flag the error.

**Comment by ksclarke** [comment]
Interesting, thanks @haschart

**Comment by haschart** [comment]
It relies on the previous change to the class Record, made with the release of 2.7.0

**Comment by ksclarke** [comment]
The upstream MARC4J project is publishing artifacts to Maven Central now and has merged in most of the changes from my fork so I'm stopping development of this fork and going to start using the upstream again.

As a result, I'm closing this issue as "Won't Fix".
