### ISSUE TITLE
Bug: parsing error by unordered directory entries

### ISSUE THREAD

**Issue by cthdev** [ksclarke/freelib-marc4j#7]
Hi,

From MARC21 record structure specs, directory entries for data fields do not have to be stored in the same order in the record. Method parseRecord() in org.marc4j.MarcStreamReader.java assumes that directory entries are ordered. How can I submit a patch?

Thanks,
Thien

**Comment by ksclarke** [comment]
If you fork the repository and make the changes in your fork, you can then submit a pull request through GitHub.

**Comment by ksclarke** [comment]
PR merged.  I need to do a little documentation cleanup and then tomorrow night will push a new version to the Maven Central repo.  Thanks!
